---
driver_plugin: vagrant
driver_config:
    require_chef_omnibus: latest

platforms:
- name: ubuntu-12.10
  run_list:
  - recipe[apt]
- name: ubuntu-12.04
  run_list:
  - recipe[apt]
suites:
- name: ldap
  run_list:
    - recipe[zarafa::ldap]
    - recipe[minitest-handler]
  attributes:
    zarafa:
      backend_type = "ldap"

- name: mysql
  run_list:
    - recipe[zarafa::mysql]
    - recipe[minitest-handler]
  attributes:
    zarafa:
      backend_type = "mysql"

- name: ldap_server
  run_list:
    - recipe[openldap::master]
    - recipe[zarafa::ldap_users]
    - recipe[zarafa::ldap_server]
    - recipe[phpldapadmin]
  attributes:
    openldap:
      rootpw: "{SSHA}6BjlvtSbVCL88li8IorkqMSofkLio58/" # secretsauce
      basedn: "dc=example, dc=com"
      server: "ldap.example.com"
      preseed_dir: "/tmp/does_not_exist"
