---
driver_plugin: vagrant
driver_config:
    require_chef_omnibus: latest

platforms:
- name: ubuntu-12.10
  run_list:
  - recipe[apt]
- name: ubuntu-12.04
  run_list:
  - recipe[apt]
suites:
- name: ldap
  run_list:
    - recipe[zarafa::ldap]
    - recipe[zarafa-test::ldap]
    - recipe[minitest-handler]
  attributes:
    zarafa:
      rootpw: "{SSHA}6BjlvtSbVCL88li8IorkqMSofkLio58/" # secretsauce
      basedn: "dc=example, dc=com"
      server: "ldap.example.com"
      preseed_dir: "/tmp/does_not_exist"

- name: mysql
  run_list:
    - recipe[zarafa::mysql]
    - recipe[zarafa-test::mysql]
    - recipe[minitest-handler]
  attributes:
    zarafa:
      manage_ssl: false
      rootpw: "{SSHA}6BjlvtSbVCL88li8IorkqMSofkLio58/" # secretsauce
      basedn: "dc=example, dc=com"
      server: "ldap.example.com"
      preseed_dir: "/tmp/does_not_exist"
